### ISSUE TITLE
Missing types (`uint64`)

### ISSUE THREAD

**Issue by abourget** [emicklei/protobuf2map#1]
I get this error when decoding a .proto that works elsewhere:

```
unknown type:uint64
```

Is it possible there are a few missing types?

**Comment by abourget** [comment]
I added a simple handling for:
```
func (d *decoder) decodeNormalField(f *pp.NormalField, wire uint64) error {
	if "uint64" == f.Type {
		return d.handleInt64(f.Name, f.Repeated)
	}
```

but then I get: `unknown type:google.protobuf.Timestamp` .. though I did load in the Definitions that element.

**Comment by emicklei** [comment]
thank you for reporting this. Sure we can add more types. I will have a look at this example more closely.
